### ISSUE TITLE
TypeError: this.tree.refresh is not a function

### ISSUE THREAD

**Issue by smroutes** [BlueMagnificent/monaco-tree#1]
Hi, I am trying to integrate this but found an issue occurred from monaco-tree.js 

TypeError: this.tree.refresh is not a function

  50 |            this.setState({ directory: props.directory });
  51 | 
  52 |        } else {
> 53 |          this.tree.refresh();
     | ^  54 |          this.expandTree(this.tree);
  55 | 
  56 |        }

**Comment by BlueMagnificent** [comment]
This has been fixed. 

Thanks
